### PR TITLE
42 grant active permission to another user

### LINKED ISSUE #42: JS-T: Grant active permission to another account (funds activity)
Advanced: Grant active permission to another account (funds activity)

**AC**

- [x] Example of use case and reference links
- [x] Grant active permission authority to other user on your account

### PR DESCRIPTION
**Pull request by roboza**
Closes #42

### CODE REVIEW

**Comment by roboza** [comment]
@relativityboy Fixed merge conflicts

**Comment by roboza** [comment]
@relativityboy busy fixing merge conflicts

**Comment by roboza** [comment]
@relativityboy This branch seems a little all over the place with the changes we made. I am going to redo this branch with the import syntax and recommit at a new -fixed branch.

**Comment by roboza** [comment]
Replaced by #124

**Comment by relativityboy** [comment]
Fixed in #124

**Pull request closed without merging**
