### PR TITLE
26 search accounts

### LINKED ISSUE #26: JS-T: Search accounts
Search accounts

**AC**

- [x] Search field to find accounts
- [x] UI to display account names

### PR DESCRIPTION
**Pull request by roboza**
Closes #26 
Updated main readme with link too.

### CODE REVIEW

**Comment by inertia186** [comment]
The tutorial **Steps** need to look closer to how it's done in this tutorial:

https://github.com/steemit/devportal-tutorials-js/blob/master/tutorials/14_reblogging_post/README.md#steps

**Comment by roboza** [comment]
@inertia186 I am not sure I understand the requirement here, the link you sent me to looks the same?

**Comment by inertia186** [comment]
I was looking at the markdown source.  Were you looking at the rendered version instead?  Maybe that's why they look the same on your end.

We have seen github's markdown rendering look different once we let jekyll render it.  I'm just trying to head off that possibility.

**Comment by relativityboy** [comment]
I updated the run instructions to conform to our current standards.

**Pull request merged**
